developer_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.mybio, name='home'),
    path("projects/", include("projects.urls")), 
    path('contact/', views.contact, name="contact")
]  

if bool(settings.DEBUG):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from projects import views

app_name = "projects"

urlpatterns = [
    path('', views.index, name="projects"),
    path('<str:pk>', views.project_detail, name="project-detail"),

    
]

projects/models.py
from django.db import models
import uuid

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='projects', blank=True, default="default.webp")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    tags = models.ManyToManyField('Tag', blank=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ("-created_at",)
    
class Tag(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    
    def __str__(self):
        return self.name

developer_portfolio/forms.py
from django import forms

class ContactForm(forms.Form):
    error_css_class = "text-red-700"
    required_css_class = "text-red-700"
    
    name = forms.CharField(max_length=100, )
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)
    
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget = forms.TextInput(attrs={
            'placeholder': 'Enter Name', 
            'required': True})

        self.fields['email'].widget = forms.EmailInput(attrs={
            'placeholder': 'Your@Email.com',
            'required': True})

        self.fields['message'].widget = forms.Textarea(attrs={
            'placeholder': 'Enter Your Message',
            'required': True})
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'w-full rounded-md p-4'

        
class Meta:
    model = ContactForm
    error_messages = {
        "name": {
            "required": "Your name must not be empty!",
            "max_length": "Please enter a shorter name!",
        },
        "email": {
            "required": "Your email address must not be empty!",
            'invalid': 'Wrong email address format. Enter email address as: your@email.com',
        },
        "message": {
            "required": "Your message must not be empty!",
        }
    }

developer_portfolio/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.conf import settings
from .forms import ContactForm

def mybio(request):
    return render(request, 'my_bio.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            subject = f"Message from Portfolio website from {name}"
            message = f"Sender's Name: {name}\nSender's Email: {email}\n\nMessage:\n{message}"

            send_mail(
                subject,
                message,
                email,
                [settings.EMAIL_ADDRESS],
                fail_silently=False,
            )

            return redirect('home')

    else:
        form = ContactForm()

    return render(request, 'contact.html', {'form': form})

projects/views.py
from django.shortcuts import render
from projects.models import Project
from projects.utils import searchProjects, paginateProjects

# Create your views here.
def index(request):
    projects, search_query = searchProjects(request)

    custom_range, projects = paginateProjects(request, projects, 6)

    context = {"results": projects,
               "search_query": search_query,
               "custom_range": custom_range}
    return render(request, 'projects/projects.html', context)

def project_detail(request, pk):
    project = Project.objects.get(id=pk)
    context = {"project": project}
    return render(request, 'projects/project-detail.html', context) 

projects/templates/projects/project-detail.html
{%extends "base.html" %}
{% block title %} | {{project.title}}{% endblock %}
{% block content %}



<!-- Main Section -->
<main class="singleProject my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <h3 class="singleProject__subtitle">Tools & Stacks</h3>

        <div class="singleProject__toolStack">
          {% for tag in project.tags.all%}
          <span class="tag tag--pill tag--sub tag--lg">
            <small>{{tag.name}}</small>
          </span>
          {% endfor %}
        </div>
        {% if project.source_link %}
        <a class="singleProject__liveLink" href="{{project.source_link}}" target="_blank"><i
            class="fa fa-external-link"></i>Source Code
        </a>
        {% endif%}

      </div>
      <div class="column column--2of3">
        <img class="singleProject__preview" src="{{project.image.url}}" alt="portfolio thumbnail" />
        <h2 class="singleProject__title">
          {% if project.demo_link %}
          <a class="singleProject__liveLink" href="{{project.demo_link}}" target="_blank"><i class="fa fa-external-link"
              size aria-hidden="true"></i>
            {{project.title}}
          </a>
          {% else %}
          {{project.title}}
          {% endif %}
        </h2>
        <h3 class="singleProject__subtitle">About the Project</h3>
        <div class="singleProject__info text-justify indent-8">
          {{project.description|linebreaks}}
        </div>

      </div>
    </div>
  </div>
  </div>
</main>


{% endblock %}

projects/templates/projects/projects.html
{% extends "base.html"%}
{% load static %}
{% block title %} | Projects{% endblock%}

{% block content %}




<!-- Main Section -->
<main class="projects">
  <section class="hero-section text-center">
    <div class="container container--narrow">
      <div class="hero-section__box">
        <h2>Search for <span>Projects</span></h2>
      </div>

      <div class="hero-section__search">
        <form id='searchForm' class="form" action="{% url 'projects:projects' %}" method="get">
          <div class="form__field">
            <label for="formInput#search">Search By Projects </label>
            <input class="input input--text" id="formInput#search" type="text" name="search_query"
              value="{{search_query}}" placeholder="Search by Project Title or Technology" />
          </div>

          <input class="btn btn--sub btn--lg" type="submit" value="Search" />
        </form>
      </div>
    </div>
  </section>

  <!-- Search Result: DevList -->
  <section class="projectsList">
    <div class="container">
      <div class="grid grid--three">

        {% for project in results %}
        <div class="column">
          <div class="card project">
            <a href="{% url 'projects:project-detail' project.id %}" class="project w-full">
              <img class="w-full h-80 object-cover" src="{{project.image.url}}" alt="{{project.name}} thumbnail" />
              <div class="card__body">
                <h3 class="project__title">{{project.title}}</h3>
                <!--
                  <p class="project--rating">
                    <span style="font-weight: bold;">{{project.vote_ratio}}</span> Positive
                    Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                  </p>
                  -->
                <div class="project__tags">
                  {% for tag in project.tags.all %}
                  <span class="tag tag--pill tag--main"><small>{{tag}}</small></span>
                  {% endfor %}
                </div>
              </div>
            </a>
          </div>
        </div>
        {% endfor %}



      </div>
    </div>
  </section>

  {% include 'includes/pagination.html' %}
</main>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <script type="module" src="{% static 'js/application.js' %}"></script>

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'images/developer-icon.svg' %}" type="image/x-icon" />
  <!-- Icon - FontAwesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
    integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!-- Mumble UI -->
  <link rel='stylesheet' type="text/css" media="screen" href="{% static 'styles/tailwindoutput.css' %}">

  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel='stylesheet' type="text/css" media="screen" href="{% static 'styles/app.css' %}">
  <title>Portfolio {% block title %}{% endblock %}</title>

</head>

<body>
  {% include "includes/navbar.html" %}
  {% block content %} {% endblock %}
</body>
<script src="{% static 'uikit/app.js' %}"></script>
<script src="{% static 'js/pagination.js' %}"></script>

</html>

templates/contact.html
{% extends "base.html"%}
{% load static %}
{% block title %} | Contact{% endblock%}

{% block content %}
<div class="container">
    <div class=" mt-16 w-full md:w-3/4 flex flex-col mx-auto gap-4">
        <div class="flex flex-row">
            <div class="basis-2/5 lg:basis-1/5 px-4 font-bold">Email Address:</div>
            <div class="basis-3/5 lg:basis-4/5 px-4">girovskyjaroslav@gmail.com</div>
        </div>
        <div class="flex flex-row">
            <div class="basis-2/5 lg:basis-1/5 px-4 font-bold">Phone Number:</div>
            <div class="basis-3/5 lg:basis-4/5 px-4">+421 911 812 199</div>
        </div>
        <div class="flex flex-row">
            <div class="basis-2/5 lg:basis-1/5 px-4 font-bold">Address:</div>
            <div class="basis-3/5 lg:basis-4/5 px-4">Veľká Tŕňa, Hlavná 124/7, Slovakia</div>
        </div>
        <div class="flex flex-row">
            <div class="basis-2/5 lg:basis-1/5 px-4 font-bold">Github Account:</div>
            <div class="basis-3/5 lg:basis-4/5 px-4">github.com/jagi113</div>
        </div>
    </div>
    <div class="mt-16 w-full md:w-3/4 mx-auto bg-gray-200 p-6 rounded-md shadow-md mb-36">
        <h2 class="text-6xl font-bold mb-4">Contact Me</h2>
        <form method="POST" action="{% url 'contact' %}" class="space-y-4">
            {% csrf_token %}

            {% for field in form %}
            <label class="block text-gray-700 text-3xl font-bold mb-4">
                {{field.label_tag}}
            </label>
            {{ field }}
            {{ field.errors }}
            {% endfor %}

            <button type="submit" class="btn btn--sub btn--lg">
                Submit
            </button>
        </form>
    </div>
</div>

{% endblock %}

templates/includes/navbar.html
{% load static %}

<header class="header">
  <div class="container container--narrow">
    <a href="{% url 'home' %}" class="header__logo">
      <span class="logo">
        <i class="fa-brands fa-python fa-2xl"></i>
        <i class="fa-brands fa-square-js fa-2xl"></i>
        <i class="fa-brands fa-react fa-2xl"></i>
      </span>

    </a>
    <nav class="header__nav">
      <input type="checkbox" id="responsive-menu" />
      <label for="responsive-menu" class="toggle-menu">
        <span>Menu</span>
        <div class="toggle-menu__lines"></div>
      </label>
      <ul class="header__menu">
        <li class="header__menuItem"><a href="{% url 'home' %}">My Bio</a></li>
        <li class="header__menuItem"><a href="{% url 'projects:projects' %}">Projects</a></li>
        <li class="header__menuItem"><a href="{% url 'contact' %}" class="btn btn--sub">Contact</a></li>
      </ul>
    </nav>
  </div>
</header>

templates/includes/pagination.html
{% if results.has_other_pages %}
<div class="pagination">
  <ul class="container">
    {% if results.has_previous %}
      <li><a href="?page={{results.previous_page_number}} " class="btn page page-link" data-page="{{results.previous_page_number}}">&#10094; Prev</a></li>
    {% endif %}
    {% for page in custom_range %}
      {% if page == results.number %}
      <li><a href="?page={{page}}" class="btn page btn--sub" data-page="{{page}}">{{page}}</a></li>
      {% else %}
      <li><a href="?page={{page}}" class="btn page page-link" data-page="{{page}}">{{page}}</a></li>
      {% endif %}
    {% endfor %}
    {% if results.has_next %}
    <li><a href="?page={{results.next_page_number}}" class="btn page page-link" data-page="{{results.next_page_number}}">Next &#10095;</a></li>
    {% endif %}
  </ul>
</div>
{% endif %}